### ISSUE TITLE
Error in log file

### ISSUE THREAD

**Issue by alfredo87** [hoot-w00t/dynhost-client#1]
Hi,
all went well until I run the service and checked the log:

"settings" -> "fallback_ip_method": script error: File not found or inaccessible

**SOLVED: install.sh has a syntax error when it creates the /etc/dynhost/scripts folder and therefore does not copy the scripts to that folder!**

**Comment by alfredo87** [comment]
Thank you for this script: it works very well. It is the only one I managed to find that actually works with OVH Dyn DNS system.
Great work... merci

**Comment by akrocynova** [comment]
Hi, thank you for your feedback :+1:

Now about the issue, I had forgotten to ceate the `/etc/dynhost/scripts` folder before copying the scripts there. 321a5f152a should fix this.
